// Spellslinger Duels - rules pack: X spells (2026-10-06).
// Wordings this round added to the card reader. Registered with registerRules() (01-core.js); the card reader joins all packs in RULE_PACK_ORDER.
registerRules({
    name: 'xspells',
    effects: [
        [/^counter target spell unless its controller pays \{(\d+)\}$/, m => ({ t: 'counter', target: 'spell', filter: 'any', unless: +m[1] })],
        [/^return all (creature|creature and planeswalker|artifact) cards with mana value (\d+) or less from your graveyard to the battlefield$/, m => ({ t: 'massReanimate', what: `${m[1].replace(' and ', ' or ')} mv${m[2]}` })],
        [/^each player mills (\d+) cards$/, m => ({ t: 'millAll', n: +m[1] })],
        [/^each player sacrifices (\d+) creatures$/, m => ({ t: 'edictN', n: +m[1] })],
        [/^create (\d+) (\d+)\/(\d+) ([a-z ]+?) creature tokens and (\d+) (food|treasure|clue) tokens$/, m => [{ t: 'token', n: +m[1], p: +m[2], q: +m[3], name: m[4], kw: [] }, { t: 'artToken', n: +m[5], kind: m[6] }]],
        [/^create a number of tapped treasure tokens equal to (?:its|~'s) power$/, () => ({ t: 'artToken', n: 0, nFrom: 'srcLastPow', kind: 'treasure', tapped: true })],
        [/^you gain life and draw cards equal to (?:its|~'s) power$/, () => [{ t: 'gain', n: 0, nFrom: 'srcLastPow' }, { t: 'draw', n: 0, nFrom: 'srcLastPow' }]],
        [/^create a (\d+)\/(\d+) ([a-z ]+?) (artifact )?creature token(?: with ([a-z ,]+))? for each \+1\/\+1 counter on (?:~|it)$/, m => ({ t: 'token', n: 0, nFrom: 'srcLastCounters', p: +m[1], q: +m[2], name: m[3], artifact: !!m[4], kw: m[5] ? splitKw(m[5]) : [] })],
        [/^draw a card for each \+1\/\+1 counter on (?:~|it)$/, () => ({ t: 'draw', n: 0, nFrom: 'srcLastCounters' })],
        [/^create a number of (\d+)\/(\d+) ([a-z ]+?) creature tokens equal to ~'s power$/, m => ({ t: 'token', n: 0, nFrom: 'srcPow', p: +m[1], q: +m[2], name: m[3], kw: [] })],
        [/^~ deals (\d+) damage to target creature\. create a number of tapped treasure tokens equal to the amount of excess damage dealt to that creature this way$/, m => ({ t: 'dmg', n: +m[1], target: 'creature', excessTreasure: true })],
        [/^search your library(?: and\/or graveyard)? for an? (?:(white|blue|black|red|green) )?(creature|artifact|permanent|enchantment) card with mana value (\d+) or less,? (?:and )?put (?:it|that card) onto the battlefield(?:, then shuffle)?$/, m => ({ t: 'tutor', what: `${m[1] ? `${m[1]} ` : ''}${m[2]} mv${m[3]}`, bf: true, gyToo: /graveyard/.test(m[0]) })],
        [/^shuffle ~ into its owner's library$/, () => ({ t: 'shuffleSelfIn' })],
        [/^~ deals (\d+) damage to each creature (without flying|with flying)? ?and each player$/, m => ({ t: 'dmgSweep', n: +m[1], filt: m[2] === 'without flying' ? 'noFly' : m[2] ? 'fly' : 'all', players: true })],
        [/^~ deals (\d+) damage to each (nonartifact )?creature and each player$/, m => ({ t: 'dmgSweep', n: +m[1], filt: m[2] ? 'nonartifact' : 'all', players: true })],
        [/^~ deals (\d+) damage to each creature without flying and each planeswalker$/, m => ({ t: 'dmgSweep', n: +m[1], filt: 'noFly' })],
        [/^target player gains (\d+) life$/, m => ({ t: 'gain', n: +m[1] })],
        [/^exile up to (\d+) target cards from graveyards$/, m => ({ t: 'exileGy', n: +m[1] })],
        [/^tap (\d+) target creatures$/, m => ({ t: 'tap', target: 'creature', multi: +m[1] })],
        [/^(destroy|exile) (?:up to )?(\d+) target (artifacts and\/or enchantments|artifacts|creatures|nonland permanents)$/, m => ({ t: m[1], target: 'perm', filter: { 'artifacts and/or enchantments': 'artifact or enchantment', artifacts: 'artifact', creatures: 'creature', 'nonland permanents': 'nonland permanent' }[m[3]], multi: +m[2] })],
        [/^counter target spell with mana value (\d+)$/, m => ({ t: 'counter', target: 'spell', filter: `mv=${m[1]}` })],
        [/^gain control of target creature with mana value (\d+)( or less)?$/, m => ({ t: 'stealPerm', target: 'creature', only: `creature with mana value ${m[1]}${m[2] ? ' or less' : ''}` })],
        [/^put (\d+) -1\/-1 counters on each creature$/, m => ({ t: 'minusEach', n: +m[1] })],
        [/^each creature gets -(\d+)\/-(\d+) until end of turn$/, m => ({ t: 'allPump', p: -m[1], q: -m[2] })],
        [/^~ deals (\d+) damage to each of up to (\w+) targets$/, m => ({ t: 'dmg', n: +m[1], target: 'any', multi: num(m[2]) })],
        [/^target player draws (\d+) cards$/, m => ({ t: 'draw', n: +m[1] })],
        [/^exile (\d+) target creatures §§ for each creature exiled this way, its controller creates a (\d+)\/(\d+) ([a-z ]+?) creature token$/, m => ({ t: 'exile', target: 'perm', filter: 'creature', multi: +m[1], ctrlToken: { p: +m[2], q: +m[3], name: m[4] } })],
        [/^create (\d+) (\d+)\/(\d+) ([a-z ]+?) creature tokens with "~ can't block\."$/, m => ({ t: 'token', n: +m[1], p: +m[2], q: +m[3], name: m[4], kw: ['cantblock'] })],
    ],
});
